### ISSUE TITLE
Make Chassis fast

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#38]
Chassis takes a long time to set up a new project. Let's fix that.
- [x] Create a base box to avoid repeating the same steps every time: #36
- [x] Investigate apt caches: #25
- [x] Move the expensive submodule cloning into the main repo: #37

What else is slow? Let's investigate.
